INSERT INTO users (nickname, password) VALUES('ben', 'password');
INSERT INTO users (nickname, password) VALUES('jane', 'password');
INSERT INTO users (nickname, password) VALUES('tom', 'password');
INSERT INTO users (nickname, password) VALUES('harry', 'password');
INSERT INTO users (nickname, password) VALUES('mary', 'password');
INSERT INTO users (nickname, password) VALUES('XiaoMing', 'password');
INSERT INTO users (nickname, password) VALUES('XiaoLi', 'password');
INSERT INTO users (nickname, password) VALUES('XiaoHong', 'password');

INSERT INTO tweets (userId, tweetmsg) VALUES(1, 'HI WORLD');
INSERT INTO tweets (userId, tweetmsg) VALUES(5, 'HELLO WORLD');
INSERT INTO tweets (userId, tweetmsg) VALUES(1, 'BANANA');
INSERT INTO tweets (userId, tweetmsg) VALUES(2, 'APPLE');
INSERT INTO tweets (userId, tweetmsg) VALUES(3, 'PINEAPPLE');
INSERT INTO tweets (userId, tweetmsg) VALUES(4, 'test test 123');
INSERT INTO tweets (userId, tweetmsg) VALUES(1, 'IT WORKS!');
INSERT INTO tweets (userId, tweetmsg) VALUES(8, 'gone');

INSERT INTO following (userid, followingid) VALUES('1', '2');
INSERT INTO following (userid, followingid) VALUES('1', '3');
INSERT INTO following (userid, followingid) VALUES('1', '5');
INSERT INTO following (userid, followingid) VALUES('1', '6');
INSERT INTO following (userid, followingid) VALUES('1', '7');
INSERT INTO following (userid, followingid) VALUES('1', '8');
INSERT INTO following (userid, followingid) VALUES('2', '1');
INSERT INTO following (userid, followingid) VALUES('2', '3');
INSERT INTO following (userid, followingid) VALUES('2', '5');
INSERT INTO following (userid, followingid) VALUES('2', '6');
INSERT INTO following (userid, followingid) VALUES('2', '7');
INSERT INTO following (userid, followingid) VALUES('2', '8');
INSERT INTO following (userid, followingid) VALUES('3', '1');
INSERT INTO following (userid, followingid) VALUES('3', '2');
INSERT INTO following (userid, followingid) VALUES('3', '5');
INSERT INTO following (userid, followingid) VALUES('3', '6');
INSERT INTO following (userid, followingid) VALUES('3', '7');
INSERT INTO following (userid, followingid) VALUES('3', '8');
INSERT INTO following (userid, followingid) VALUES('4', '1');
INSERT INTO following (userid, followingid) VALUES('4', '2');
INSERT INTO following (userid, followingid) VALUES('4', '3');
INSERT INTO following (userid, followingid) VALUES('4', '5');
INSERT INTO following (userid, followingid) VALUES('4', '6');
INSERT INTO following (userid, followingid) VALUES('4', '7');
INSERT INTO following (userid, followingid) VALUES('4', '8');
INSERT INTO following (userid, followingid) VALUES('5', '1');
INSERT INTO following (userid, followingid) VALUES('5', '6');
INSERT INTO following (userid, followingid) VALUES('6', '1');
INSERT INTO following (userid, followingid) VALUES('6', '2');
INSERT INTO following (userid, followingid) VALUES('6', '3');
INSERT INTO following (userid, followingid) VALUES('6', '4');
INSERT INTO following (userid, followingid) VALUES('6', '5');
INSERT INTO following (userid, followingid) VALUES('6', '7');
INSERT INTO following (userid, followingid) VALUES('6', '8');
INSERT INTO following (userid, followingid) VALUES('7', '3');
INSERT INTO following (userid, followingid) VALUES('7', '8');
INSERT INTO following (userid, followingid) VALUES('8', '1');
INSERT INTO following (userid, followingid) VALUES('8', '2');
INSERT INTO following (userid, followingid) VALUES('8', '3');
INSERT INTO following (userid, followingid) VALUES('8', '7');