INSERT INTO payments (sender_id,recipient_id,amount) VALUES (1,18,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (1,20,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (1,21,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (1,15,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (1,16,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (3,18,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (3,20,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (3,21,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (3,15,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (3,16,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (4,18,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (4,20,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (4,21,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (4,15,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (4,16,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (5,18,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (5,20,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (5,21,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (5,15,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (5,16,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (8,18,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (8,20,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (8,21,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (8,15,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (8,16,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (12,18,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (12,20,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (12,21,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (12,15,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (12,16,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (13,18,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (13,20,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (13,21,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (13,15,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (13,16,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (14,18,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (14,20,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (14,21,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (14,15,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (14,16,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (15,18,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (15,20,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (15,21,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (15,14,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (15,16,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (16,18,188);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (16,20,50);
INSERT INTO payments (sender_id,recipient_id,amount) VALUES (16,21,188);

-- INSERT INTO tweets (users_id,content,timestamp) VALUES (5,'During World War II, my grandpa single-handedly killed 30 German pilots. He was the crappiest mechanic the Luftwaffe ever hired.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (5,'8 p.m. I get a text from my girlfriend: “Me or football?” 11 p.m. I text my girlfriend: “You of course!”','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (5,'“I made cookies for you. It is an apology for crashing your car.” “YOU DID WHAT?!” “Cookies. I made cookies for you!”','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (5,'Today I ran from a ticket inspector. He chased me through half the train. When he finally caught me, he wasn’t very amused to find that I actually had a ticket.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (5,'When I see lovers names carved in a tree, I dont think it is sweet. I just think it is surprising how many people bring a knife on a date.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (8,'Why I feel Christmas is just like a day at the office? Because you do all the work and then this fat guy with the suit gets all the credit!','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (8,'Lazy people fact #28492124. You were too lazy to read that number.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (8,'I used to hate marriages since my aunts always told me that I was next. They stopped when I started telling them the same thing at funerals.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (12,'When its my time to go I want to die peacefully in my sleep like my grandfather and not screaming in terror like all his passengers did.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (12,'I dreamed I was forced to eat a giant marshmallow. When I woke up, my pillow was gone.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (12,'Whats the big deal about flag burning? I know its a symbol of America. So what? So is apple pie - my mother used to burn those all the time.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (12,'A programmer is told to "go to hell", he finds the worst part of that statement is the "go to"','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (13,'Q: How many programmers does it take to screw in a light bulb? A: None. Its a hardware problem.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (13,'A programmer puts two glasses on his bedside table before going to sleep. A full one, in case he gets thirsty, and an empty one, in case he doesnt.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (13,'In order to understand recursion you must first understand recursion.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (13,'A SQL statement walks into a bar and sees two tables. It approaches, and asks “may I join you?”','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (13,'An SEO expert walks into a bar, pub, liquor store, brewery, alcohol, beer, whiskey, vodka','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (13,'Two programmers walk into a foo.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (14,'Why do programmers take so long in the shower? They read the directions on the shampoo bottle and follow them to the letter: Lather, rinse, and repeat.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (14,'Why did the two functions stop calling each other? Because they had constant arguments.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (15,'The programmer quit his job because he didnt get arrays','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (16,'"Honey, go to the store and buy some eggs." "OK." "Oh and while youre there, get some milk."He never returned.','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (16,'I tell you a joke about UDP, but Im not sure you get it...','now',);
-- INSERT INTO tweets (users_id,content,timestamp) VALUES (16,'What do you call a programmer who has thrown up at IHOP? A stack overflow.','now',);