INSERT INTO userdb (userhandle,password) VALUES ('Bobby123','1234');
INSERT INTO userdb (userhandle,password) VALUES ('Sally_55','1234');
INSERT INTO userdb (userhandle,password) VALUES ('ma_name_jeff','1234');

INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('1','Bobby123','I am the bobby123 user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('1','Bobby123','I am the bobby123 user of twitter I am the bobby123 user of twitter I am the bobby123 user of twitter I am the bobby123 user of twitter I am the bobby123 user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('1','Bobby123','I am the bobby123 user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('1','Bobby123','I am the bobby123 user of twitter I am the bobby123 user of twitter I am the bobby123 user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('1','Bobby123','I am the bobby123 user of twitterI am the bobby123 user of twitterI am the bobby123 user of twitterI am the bobby123 user of twitterI am the bobby123 user of twitterI am the bobby123 user of twitterI am the bobby123 user of twitterI am the bobby123 user of twitterI am the bobby123 user of twitterI am the bobby123 user of twitterI am the bobby123 user of twitterI am the bobby123 user of twitterI am the bobby123 user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('1','Bobby123','I am the bobby123 user of twitterI am the bobby123 user of twitterI am the bobby123 user of twitterI am the bobby123 user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('1','Bobby123','I am the bobby123 user of twitter');

INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('2','Sally_55','I am the sallllyy user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('2','Sally_55','I am the sally555555 user of twitter I am the sally555555 user of twitter I am the sally555555 user of twitter I am the sally555555 user of twitter I am the sally555555 user of twitterr of twitterI am the sally555555 user of twitterI am the sally555555 user of twitterI am the sally555555 user of twitterI am the sally555555 user of twitterI am the sally555555 user of twitterI am the sally555555 user of twitterI am ');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('2','Sally_55','I am the sally555555 user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('2','Sally_55','I am the sally555555 user of twitter I am the sally555555 user of twitter I am the sally555555 user of twitterr of twitterI am the sally555555 user of twitterI am the sally555555 user of twitterI am the sally555555 user of twitterI am the sally555555 user of twitterI am the sally555555 user of twitterI am the sally555555 user of twitterI am ');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('2','Sally_55','I am the sally555555 user of twitterI am the sally555555 user of twitterI am the sally555555 user of twitterI am the sally555555 user of twitterI am the sally555555 usethe sally555555 user of twitterI am the sally555555 user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('2','Sally_55','I am the sally555555 user of twitterI am the sally555555 user of twitterI am the sally555555 user of twitterI am the sally555555 user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('2','Sally_55','I am the sally555555 user of twitter');

INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('3','ma_name_jeff','ser of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the fI am the MAA NAME JEFFFF user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('3','ma_name_jeff','I am the MAA NAME JEFFFF user of twitter I am the MAA NAME JEFFFF user of twitter I am the MAA NAME JEFFFF user of twitter I am the MAA NAME JEFFFF user of twitter I am the MAA NAME JEFFFF user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('3','ma_name_jeff','ser of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user---------MA NAME JEFF---------ser of twitterI am the fser of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the fI am the MAA NAME JEFFFF user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('3','ma_name_jeff','ser of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the fI am the MAA NAME JEFFFF user of twitter I am the MAA NAME JEFFFF user of twitter I am the MAA NAME JEFFFF user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('3','ma_name_jeff','I am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF uirst user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('3','ma_name_jeff','I am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitter');
INSERT INTO tweetsdb (userid,userhandle,tweets) VALUES ('3','ma_name_jeff','ser of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the fser of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the fser of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the MAA NAME JEFFFF user of twitterI am the fI am the MAA NAME JEFFFF user of twitter');