INSERT INTO tweets (detail, created, edited, user_id) VALUES('hello i am john', '1 Jan 2020', '1 Jan 2020', 1);
INSERT INTO tweets (detail, created, edited, user_id) VALUES('hello i am adrian', '1 Jan 2020', '1 Jan 2020', 2);
INSERT INTO tweets (detail, created, edited, user_id) VALUES('hello i am mr bean', '1 Jan 2020', '1 Jan 2020', 3);
INSERT INTO tweets (detail, created, edited, user_id) VALUES('hello i am dinosaur', '1 Jan 2020', '1 Jan 2020', 4);
INSERT INTO tweets (detail, created, edited, user_id) VALUES('hello i am potato', '1 Jan 2020', '1 Jan 2020', 5);
INSERT INTO tweets (detail, created, edited, user_id) VALUES('hello this is my 2nd post', '1 Jan 2020', '1 Jan 2020', 2);
INSERT INTO tweets (detail, created, edited, user_id) VALUES('hello this is my 2nd post', '1 Jan 2020', '1 Jan 2020', 3);
INSERT INTO tweets (detail, created, edited, user_id) VALUES('hello this is my 2nd post', '1 Jan 2020', '1 Jan 2020', 4);
INSERT INTO tweets (detail, created, edited, user_id) VALUES('hello this is my 2nd post', '1 Jan 2020', '1 Jan 2020', 5);
INSERT INTO tweets (detail, created, edited, user_id) VALUES('hello this is my 2nd post', '1 Jan 2020', '1 Jan 2020', 1);